Dropbox actuallty requires the apache http library(ies) ava.lang.NoClassDefFoundError: org/apache/http/HttpEntity 	at com.github.fge.fs.dropbox.driver.DropBoxFileSystemDriver.newWatchService(DropBoxFileSystemDriver.java:426)